### ISSUE TITLE
Hello, quick question

### ISSUE THREAD

**Issue by MostHated** [davidwhitney/ReallySimpleEventing#7]
Hey there,
    Forgive me for such a silly question but I am new to the network side of programming. In your opinion, would this end up being a good idea to use in a video game using Unity3d for online play and sending event messages?

Thanks!

**Comment by davidwhitney** [comment]
Hey - At the moment this library doesn't target Mono - so wouldn't be a good fit for a Unity project - it's for use in "inside-app-domain" messaging.

Not the droids you're looking for :) But a similar pattern would work well.

**Comment by MostHated** [comment]
Ah, no problem, thanks!
